(*
The MIT License (MIT)
Copyright (c) 2025 [WE THE DEVS].

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *)

(*
 * Project      : ANTLR4 lexer grammar for NeoBASIC programming language.
 *                https://github.com/neobasic
 * Developed by : Raul Bras, @teknolista.
 *)

(* IDENTIFICATION DIVISION *)

MODULE = "module" .
ALGORITHM = "algorithm" .
NOTABENE = "notabene" .

(* ENVIRONMENT DIVISION *)

USE = "use" .
AS = "as" .
OF = "of" .
INCLUDE = "include" .
INTERFACE = "interface" .
RPC = "rpc" .
EXTERN = "extern" .

(* API TYPES *)

SOCKET = "socket" .
HTTP = "http" .
HTTPS = "https" .
REST = "rest" .
SOAP = "soap" .
GRPC = "grpc" .
AMQP = "amqp" .
FTP = "ftp" .
SMTP = "smtp" .
IMAP = "imap" .
POP3 = "pop3" .

(* MAGIC COMMENT: TEST *)

UNIT = "unit" .
FROM = "from" .
ONCE = "once" .
DATA = "data" .
CALL = "call" .
HIDE = "hide" .
SHOW = "show" .
INTO = "into" .
PASS = "pass" .
PAST = "past" .
FAIL = "fail" .

(* TOP LEVEL SENTENCES *)

DEF = "def" .
DEFN = "defn" .
UNDEF = "undef" .
TYPE = "type" .
CONST = "const" .
VAL = "val" .
VAR = "var" .
FACT = "fact" .
FEED = "feed" .
FMAP = "fmap" .
FUNC = "func" .
SUB = "sub" .
EVENT = "event" .
ENUM = "enum" .
STRUCT = "struct" .
PROTO = "proto" .
TRAIT = "trait" .
CLASS = "class" .

(* STATEMENTS AND BLOCKS *)

DEFER = "defer" .
WITH = "with" .
DO = "do" .
IF = "if" .
THEN = "then" .
ELSE = "else" .
UNLESS = "unless" .
CASE = "case" .
MATCH = "match" .
FALLTHROUGH = "fallthrough" .
TRY = "try" .
CATCH = "catch" .
RETRY = "retry" .
ORELSE = "orelse" .
LOOP = "loop" .
TIMES = "times" .
FOR = "for" .
EACH = "each" .
STEP = "step" .
WHILE = "while" .
UNTIL = "until" .
NEXT = "next" .
REDO = "redo" .
BREAK = "break" .
CONTINUE = "continue" .
RETURN = "return" .
YIELD = "yield" .
INVAR = "invar" .
GO = "go" .
TO = "to" .
ASYNC = "async" .
THREAD = "thread" .
TASK = "task" .
NODE = "node" .
AWAIT = "await" .
ALL = "all" .
SWITCH = "switch" .
WHEN = "when" .
DEFAULT = "default" .

(* PREDECLARED VALUES AND VARIABLES *)

THIS = "this" .
IOTA = "iota" .
NTH = "nth" .
ONE = "one" .
END = "end" .
IT = "it" .
SELF = "self" .
SUPER = "super" .

(* FACT MODIFIERS *)

ALL = "all" .
ANY = "any" .
ONE = "one" .
TWO = "two" .
NIL = "nil" .

(* EXPRESSIONS *)

LET = "let" .
GET = "get" .
SET = "set" .

(* MISCELLANEOUS OPERATORS *)

TYPEOF = "typeof" .
INSTANCEOF = "instanceof" .
SIZEOF = "sizeof" .
NEW = "new" .
DEL = "del" .
IS = "is" .
IN = "in" .
BETWEEN = "between" .
LIKE = "like" .

(* LOGICAL OPERATORS *)

NOT = "not" .
AND = "and" .
NAND = "nand" .
OR = "or" .
NOR = "nor" .
XOR = "xor" .
NXOR = "nxor" .

(* MISCELLANEOUS DATA TYPES *)

NUMBER = "Number" .
TANY = "Any" .
ATOM = "Atom" .
VOID = "Void" .

(* SHELL DATA TYPES *)

URI = "Uri" .
PATH = "Path" .
FILE = "File" .

(* BOOLEAN DATA TYPES *)

BOOL8 = "Bool8" .
BOOL16 = "Bool16" .
BOOL32 = "Bool32" .
BOOL64 = "Bool64" .
BOOL128 = "Bool128" .
BOOL = "Bool" .

(* NUMERIC DIGITS *)

DIG = "Dig" .
BIT = "Bit" .
OCT = "Oct" .
HEX = "Hex" .
NIBBLE = "Nibble" .

(* NATURAL NUMBERS *)

NAT8 = "Nat8" .
NAT16 = "Nat16" .
NAT32 = "Nat32" .
NAT64 = "Nat64" .
NAT128 = "Nat128" .
BYTE = "Byte" .
NAT = "Nat" .
ASCII = "Ascii" .
CHAR = "Char" .

(* NUMERIC INTEGERS *)

INT8 = "Int8" .
INT16 = "Int16" .
INT32 = "Int32" .
INT64 = "Int64" .
INT128 = "Int128" .
INT = "Int" .
BIGINT = "Bigint" .

(* NUMERIC DECIMALS *)

DEC1 = "Dec1" .
DEC2 = "Dec2" .
DEC3 = "Dec3" .
DEC4 = "Dec4" .
DEC5 = "Dec5" .
DEC6 = "Dec6" .
DEC7 = "Dec7" .
DEC8 = "Dec8" .
DEC = "Dec" .
MONEY = "Money" .
BIGDEC = "Bigdec" .

(* NUMERIC REALS *)

REAL8 = "Real8" .
REAL16 = "Real16" .
REAL32 = "Real32" .
REAL64 = "Real64" .
REAL128 = "Real128" .
REAL = "Real" .
BIGREAL = "Bigreal" .

(* NUMERIC RATIOS *)

RATIO16 = "Ratio16" .
RATIO32 = "Ratio32" .
RATIO64 = "Ratio64" .
RATIO128 = "Ratio128" .
RATIO = "Ratio" .

(* NUMERIC COMPLEXES *)

COMPLEX16 = "Complex16" .
COMPLEX32 = "Complex32" .
COMPLEX64 = "Complex64" .
COMPLEX128 = "Complex128" .
COMPLEX = "Complex" .

(* NUMERIC QUATERNIONS *)

QUATERN32 = "Quatern32" .
QUATERN64 = "Quatern64" .
QUATERN128 = "Quatern128" .
QUATERN256 = "Quatern256" . 
QUATERN = "Quatern" .

(* TEMPORAL DATA TYPES *)

DATE = "Date" .
ELAPSE = "Elapse" .

(* SEQUENCE DATA TYPES *)

STRING = "Str" .
REGEX = "Regex" .
BINARY = "Binary" .

(* SHELL DATA TYPES *)

PATH = "Path" .
URI = "Uri" .
INET = "Inet" .

(* COMPOSITE DATA TYPES *)

RANGE = "Range" .
MAP = "Map" .

(* ARRAY DATA TYPES *)

ARRAY = "Array" .
TUPLE = "Tuple" .
LIST  = "List" .
DICT  = "Dict" .
CHAN  = "Chan" .
VEC   = "Vec" .
MAT   = "Mat" .
TSET  = "Set" .
QUEUE = "Queue" .
DEQUE = "Deque" .
XML   = "Xml" .
TABLE = "Table" .
MEMO  = "Memo" .

(* MONAD LOGIC VALUE CONSTRUCTORS *)

TRUE = "True" .
FALSE = "False" .

(* MONAD NUMERIC VALUE CONSTRUCTORS *)

NONZERO = "Nonzero" .
ZERO = "Zero" .
MINVALUE = "MinValue" .
MAXVALUE = "MaxValue" .
NAN = "NaN" .
POSITIVEINFINITY = "PositiveInfinity" .
NEGATIVEINFINITY = "NegativeInfinity" .

(* MONAD TEMPORAL VALUE CONSTRUCTORS *)

LOCALDATE = "LocalDate" .
LOCALDATETIME = "LocalDateTime" .
OFFSETDATE = "OffsetDate" .
OFFSETDATETIME = "OffsetDateTime" .
ZONEDDATE = "ZonedDate" .
ZONEDDATETIME = "ZonedDateTime" .
TOMORROW = "Tomorrow" .
NOW = "Now" .
TODAY = "Today" .
YESTERDAY = "Yesterday" .
EON = "Eon" .
EPOCH = "Epoch" .

(* MONAD SEQUENCE VALUE CONSTRUCTORS *)

BLANK = "Blank" .
NONBLANK = "Nonblank" .

(* MONAD PATH VALUE CONSTRUCTORS *)

FOLDER = "Folder" .
FILE = "File" .
LINKLINKFILE = "LinkFile" .
PIPEFILE = "PipeFile" .
SOCKETFILE = "SocketFile" .
BLOCKDEVICE = "BlockDevice" .
CHARDEVICE = "CharDevice" .
NULLDEVICE = "NullDevice" .

(* MONAD URI VALUE CONSTRUCTORS *)

URL = "Url" .
URN = "Urn" .

(* MONAD INET VALUE CONSTRUCTORS *)

IPV4 = "Ipv4" .
IPV6 = "Ipv6" .

(* MONAD MAYBE VALUE CONSTRUCTORS *)

SOME = "Some" .
NONE = "None" .

(* MONAD EITHER VALUE CONSTRUCTORS *)

YEA = "Yea" .
NAY = "Nay" .

(* MONAD STREAM VALUE CONSTRUCTORS *)

DATA = "Data" .
EOT = "EoT" .

(* MONAD RESULT VALUE CONSTRUCTORS *)

OKAY = "Okay" .
FAIL = "Fail" .

(* ------------------------------------------------------------------------- *)

(* CONSOLE MACROS *)

AT = "at" .
ENTER = "enter" .
PRINT = "print" .
ALERT = "alert" .
ENTRY = "entry" .
TILL = "till" .
SINCE = "since" .
TIMELY = "timely" .
CANCEL = "cancel" .
PLAY = "play" .
CLS = "cls" .

(* MAGIC COMMENT: TWEET TRACING *)

TRACE = "trace" .
DEBUG = "debug" .
INFO = "info" .
WARN = "warn" .
ERROR = "error" .
FATAL = "fatal" .
