(* DIGITS *)

decimal_digit  = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" .

decimal_groups = decimal_digit { [ "_" | "." ] decimal_digit } .


(* INTEGER LITERALS *)

decimal_integer = decimal_groups .


(* REAL LITERALS *)

decimal_point    = "," .

decimal_mantissa = decimal_groups decimal_point [ decimal_groups ] |
                   decimal_point decimal_groups |
                   decimal_groups .
decimal_exponent = ( "e" | "E" ) [ "+" | "-" ] decimal_groups .

decimal_real     = decimal_mantissa [ decimal_exponent ] .


(* IMAGINARY LITERALS *)

imaginary_unit = "i" .
